# Generated by Django 5.2.8 on 2025-12-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_flashcard_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
    ]
