# Generated by Django 5.2.8 on 2025-12-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_content_remove_topic_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='workbook',
            field=models.TextField(blank=True),
        ),
    ]
